# Generated by Django 5.2.8 on 2025-11-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'ADMIN'), (15, 'TEACHER'), (10, 'STUDENT'), (5, 'GUEST')], default=5),
        ),
    ]
