# Generated by Django 5.2.11 on 2026-02-25 09:34

from django.db import migrations


def seed_grade_levels(apps, schema_editor):
    GradeLevel = apps.get_model('db', 'GradeLevel')

    GradeLevel.objects.update_or_create(
        level='10',
        name='Grade 10',
    )

    GradeLevel.objects.update_or_create(
        level='11',
        name='Grade 11',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0002_academicyear_course_courseoffering_enrollment_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_grade_levels),
    ]
