# Generated by Django 5.2.11 on 2026-02-25 09:39

from django.db import migrations


def seed_academic_years(apps, schema_editor):
    AcademicYear = apps.get_model('db', 'AcademicYear')

    AcademicYear.objects.update_or_create(
        name='2024-2025',
        start_date='2024-01-01',
        end_date='2025-12-31',
    )
    AcademicYear.objects.update_or_create(
        name='2025-2026',
        start_date='2025-01-01',
        end_date='2026-12-31',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0003_auto_20260225_1504'),
    ]

    operations = [
        migrations.RunPython(seed_academic_years),
    ]
