# Generated by Django 5.2.11 on 2026-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_conversation_alter_user_role_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
