# Generated by Django 5.2.8 on 2025-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='payment_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='payment_year',
            field=models.PositiveIntegerField(),
        ),
    ]
