# Generated by Django 5.2.8 on 2025-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
